# Generated by Django 4.0.5 on 2022-06-26 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_active_product_featured_product_timestemp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='timestemp',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 27, 1, 20, 59, 98262)),
        ),
    ]
