# Generated by Django 4.0.5 on 2022-06-29 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GusetEmail',
            new_name='GuestEmail',
        ),
    ]
