# Generated by Django 4.0.5 on 2022-07-19 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('addresses', '0001_initial'),
        ('carts', '0002_cart_subtotal'),
        ('orders', '0007_order_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('Status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('refunded', 'Refunded')], default='created', max_length=255)),
                ('post_status', models.CharField(default='deleted', max_length=255)),
                ('Shipping_total', models.DecimalField(decimal_places=2, default=5.99, max_digits=100)),
                ('Order_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('Active', models.BooleanField(default=True)),
                ('Timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('Billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billingaddress', to='addresses.address')),
                ('Billing_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billingprofile', to='billing.billingprofile')),
                ('Cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.cart')),
                ('Shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shippingaddress', to='addresses.address')),
            ],
        ),
    ]
