# Generated by Django 4.0.5 on 2022-07-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_log',
            name='Cart',
        ),
        migrations.AlterField(
            model_name='order_log',
            name='Active',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order_log',
            name='Billing_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order_log',
            name='Billing_profile',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order_log',
            name='Order_total',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order_log',
            name='Shipping_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order_log',
            name='Shipping_total',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order_log',
            name='Timestamp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
